[project]
name = "csv-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain==0.3.24",
    "langchain-google-genai==2.1.4",
    "mysql-connector-python==9.3.0",
]
